version: '3.5'
services:
  mtproxy:
    container_name: mtproxy
    build: .
    image: mtproxy:python
    restart: unless-stopped
    #ports:
    #  - "127.0.0.1:8443:443"
    #  - "::1:8443:443"
    volumes:
      - ./config.py:/home/tgproxy/config.py
      - ./mtprotoproxy.py:/home/tgproxy/mtprotoproxy.py
    networks:
      - backend
  web:
    container_name: mtproxy-web
    image: nginx:alpine
    volumes:
      - ./index.html:/var/www/index.html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/mtproxy-tls.sharik.network/fullchain.pem:/etc/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/mtproxy-tls.sharik.network/privkey.pem:/etc/ssl/privkey.pem:ro
    networks:
      - backend
    #ports:
    #  - "127.0.0.1:9443:443"
    #  - "::1:9443:443"
    restart: unless-stopped
  proxy:
    container_name: mtproxy-proxy
    image: haproxy:alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    network_mode: "host"
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    dirver: bridge
    name: mtproxy
